AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-pipeline
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./index-photos
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::093302234862:role/service-role/index-photos-role-wokvfd18'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
      VpcConfig:
        SecurityGroupIds:
          - sg-a3509190
        SubnetIds:
          - subnet-9f8c33c0
          - subnet-d1da68b7
  Bucket1:
    Type: 'AWS::S3::Bucket'
