AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: index-photos
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode
      Description: 'index-photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::093302234862:role/service-role/index-photos-role-wokvfd18'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1